name: "Upload 40k-Weapons-Mod"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Development/40k-Weapons-Mod-Dev/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3174514408
          path: "Weapon Mods/Development/40k-Weapons-Mod-Dev"
          changelog: ${{ github.event.head_commit.message }}                  
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
