name: "Upload StarCore Enabler Rewards"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/SpraysAddon-StarCore Enabler Rewards/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2961654766
          path: "Utility Mods/Stable/SpraysAddon-StarCore Enabler Rewards"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
