name: "Upload AMP-Aristeas-Melee-Pack"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Stable/AMP-Aristeas-Melee-Pack/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2870210922
          path: "Weapon Mods/Stable/AMP-Aristeas-Melee-Pack"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}