name: "Upload Anomaly_Solaris_Hypernautics"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Stable/Anomaly_Solaris_Hypernautics/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2983399274
          path: "Weapon Mods/Stable/Anomaly_Solaris_Hypernautics"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
