name: "Upload to SCCleanDLCCattegories"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/SCCleanModCategories/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2893360222
          path: "Utility Mods/Stable/SCCleanModCategories"
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
