name: C# Syntax Check

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    name: Check Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust this to the version you are using

    - name: Syntax Check
      run: dotnet build --no-incremental --no-dependencies -c Release --verbosity quiet
