name: "Upload I NEED MORE JETPACK ACCELERATION"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/I NEED MORE JETPACK ACCELERATION/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2899738923
          path: "Utility Mods/Stable/I NEED MORE JETPACK ACCELERATION"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
