name: "Upload OnyxArmamentCo"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Stable/OnyxArmamentCo/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3123483745
          path: "Weapon Mods/Stable/OnyxArmamentCo"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
