name: "Upload PickmeRevengeance"

on:
  push:
    branches:
      - main
    paths:
      - "Gamemode Mods/Stable/PickmeRevengeance/**"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2986589130
          path: "Gamemode Mods/Stable/PickmeRevengeance"
          changelog: ${{ github.event.head_commit.message }}          
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
