name: "Upload RTS Logarithmic Angular Dev"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Development/SC_RelativeTopSpeed_Logarithmic_Angular-Dev/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3199814872
          path: "Utility Mods/Development/SC_RelativeTopSpeed_Logarithmic_Angular-Dev"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
