name: "Upload SC_HitSounds"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/SC_HitSounds/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3173935498
          path: "Utility Mods/Stable/SC_HitSounds"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
