name: "Upload StarCore Impact Sound Replacement"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/StarCore Impact Sound Replacement/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2832531817
          path: "Utility Mods/Stable/StarCore Impact Sound Replacement"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
