name: "Upload Starcore_Pointslist"

on:
  push:
    branches:
      - main
    paths:
      - "Gamemode Mods/Stable/Starcore_Pointslist/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2862022197
          path: "Gamemode Mods/Stable/Starcore_Pointslist"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
