name: "Upload to Starcore Reaction Control System"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/Starcore Reaction Control System/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2973091771
          path: "Utility Mods/Stable/Starcore Reaction Control System"
          changelog: ${{ github.event.head_commit.message }}                
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
