name: "Upload StarCoreCTF"

on:
  push:
    branches:
      - main
    paths:
      - "Gamemode Mods/Stable/StarCoreCTF/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3018817811
          path: "Gamemode Mods/Stable/StarCoreCTF"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
