name: "Upload Starcore_Pointslist-Dev"

on:
  push:
    branches:
      - main
    paths:
      - "Gamemode Mods/Development/Starcore_Pointslist-Dev/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3017849106
          path: "Gamemode Mods/Development/Starcore_Pointslist-Dev"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
