name: "Upload Starcore_Serpent_Arms_Heavy_Metal_Dev"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3211537839
          path: "Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev"
          changelog: ${{ github.event.head_commit.message }}            
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
