name: "Upload Starcore Character Edits and Proximity Entry"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/Starcore Character Edits and Proximity Entry/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2911191352
          path: "Utility Mods/Stable/Starcore Character Edits and Proximity Entry"
          changelog: ${{ github.event.head_commit.message }}           
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
