name: "Upload StarCoreCoresAddon"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/StarCoreCoresAddon/**"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3034186044
          path: "Utility Mods/Stable/StarCoreCoresAddon"
          changelog: ${{ github.event.head_commit.message }}          
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
