name: "Upload Starcore_Serpent_Arms_Heavy_Metal"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Stable/Starcore_Serpent_Arms_Heavy_Metal/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2683126590
          path: "Weapon Mods/Stable/Starcore_Serpent_Arms_Heavy_Metal"
          changelog: ${{ github.event.head_commit.message }}            
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
