name: "Upload Starcore-MA-Weapons-Natemod-Dev"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Development/Starcore-MA-Weapons-Natemod-Dev/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3017832153
          path: "Weapon Mods/Development/Starcore-MA-Weapons-Natemod-Dev"
          changelog: ${{ github.event.head_commit.message }}             
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
