name: "Upload StarCore MagicWeps"

on:
  push:
    branches:
      - main
    paths:
      - "Weapon Mods/Stable/StarCore MagicWeps/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2883286527
          path: "Weapon Mods/Stable/StarCore MagicWeps"
          changelog: ${{ github.event.head_commit.message }}             
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
