name: "Upload StarCore Tournament Weapon Category"

on:
  push:
    branches:
      - main
    paths:
      - "Utility Mods/Stable/StarCore Tournament Weapon Category/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 2785856511
          path: "Utility Mods/Stable/StarCore Tournament Weapon Category"
          changelog: ${{ github.event.head_commit.message }}             
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
