name: Aristeas UniversalUpload Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      #- uses: actions/checkout@v4.1.4
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"value\":893434534}, {\"value\":3405893405}, {\"value\":345098341}]}" >> $GITHUB_OUTPUT
  
  workshop-upload:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - run: |
          echo "${{ matrix.value }}"
      
