name: Aristeas UniversalUpload Test
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.1.4
      - id: set-matrix
        run: |
          mods=()
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}); do
            if [[ -f "$(dirname $file)/modinfo.sbmi" ]]; then
              modPath=$(dirname $file)
              modId=$(grep -oP '(?<=<Id>)\d+(?=</Id>)' "$modPath/modinfo.sbmi")
              if [[ ! " ${mods[@]} " =~ " {\"value\":$modId,\"path\":\"$modPath\"} " ]]; then
                mods+=("{\"value\":$modId,\"path\":\"$modPath\"}")
              fi
            fi
          done
          matrix=$(IFS=,; echo "${mods[*]}")
          echo "matrix={\"include\":[$matrix]}" >> $GITHUB_OUTPUT
  
  workshop-upload:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Delay
        run: sleep $((${{ strategy.job-index }} * 10))
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          login: true
          publishedFileID: ${{ matrix.value }}
          path: ${{ matrix.path }}
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}