name: Aristeas UniversalUpload Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      #- uses: actions/checkout@v4.1.4
      - id: matrix
        run: |
           echo "matrix={\"include\":[{\"value\":[352345,12345425642,1341232]}]}" >> $GITHUB_OUTPUT
  
  workshop-upload:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
      
